In [1]:
import pandas as pd
import numpy as np
import seaborn as sns # For pairplots and heatmaps
import matplotlib.pyplot as plt
import glob

In [2]:
data_path = "/Users/mdraihanmia/Ubicomp/PMNL/MotEv/MotorEvaluation/analysis/ExperimentalAnalysis/FeasibilityTesting/Data/"

In [4]:
merged_df = []
for file_name in glob.glob(data_path+'*.csv'):
    print(file_name)
    df = pd.read_csv(file_name)
    merged_df.append(df)
    # print(df.columns)
    # df = pd.concat([df, pd.read_csv(file_name)],axis=0, ignore_index=True, sort=False)
df_data = pd.concat(merged_df)
df_data

/Users/mdraihanmia/Ubicomp/PMNL/MotEv/MotorEvaluation/analysis/ExperimentalAnalysis/FeasibilityTesting/Data/P31.csv
/Users/mdraihanmia/Ubicomp/PMNL/MotEv/MotorEvaluation/analysis/ExperimentalAnalysis/FeasibilityTesting/Data/Discovery_World_Day2.csv
/Users/mdraihanmia/Ubicomp/PMNL/MotEv/MotorEvaluation/analysis/ExperimentalAnalysis/FeasibilityTesting/Data/P30.csv
/Users/mdraihanmia/Ubicomp/PMNL/MotEv/MotorEvaluation/analysis/ExperimentalAnalysis/FeasibilityTesting/Data/Discovery_World_Day1.csv
/Users/mdraihanmia/Ubicomp/PMNL/MotEv/MotorEvaluation/analysis/ExperimentalAnalysis/FeasibilityTesting/Data/P29.csv

,user_id,name,age,location,used_hand,study_id,study_day,try_allowed,try_number,try_remaining,study_start,study_end,game_type,star_time,end_time,total_time,data
0,BV4KUO,P31,2015-12-24,Lab,Right,19,Day-1,50,18,32,2023-06-19 19:04:05.183477+00:00,2023-06-19 19:23:11.666561+00:00,at_the_market,2023-06-19 14:06:12+00:00,2023-06-19 14:07:06+00:00,54,"'movement_paths': [""{'start_time': '2023-06-19..."
1,BV4KUO,P31,2015-12-24,Lab,Right,19,Day-1,50,18,32,2023-06-19 19:04:05.183477+00:00,2023-06-19 19:23:11.666561+00:00,at_the_market,2023-06-19 14:06:12+00:00,2023-06-19 14:07:14+00:00,62,"'movement_paths': [""{'start_time': '2023-06-19..."
2,BV4KUO,P31,2015-12-24,Lab,Right,19,Day-1,50,18,32,2023-06-19 19:04:05.183477+00:00,2023-06-19 19:23:11.666561+00:00,tracking_test,2023-06-19 14:07:17+00:00,2023-06-19 14:07:31+00:00,14,"{'path': [{78.5, 582.5}, {81, 581.5}, {92.5, 5..."
3,BV4KUO,P31,2015-12-24,Lab,Right,19,Day-1,50,18,32,2023-06-19 19:04:05.183477+00:00,2023-06-19 19:23:11.666561+00:00,tracking_test,2023-06-19 14:07:41+00:00,2023-06-19 14:08:00+00:00,19,"{'path': [, {1009, 276}, {1019.5, 274.5}, {102..."
4,BV4KUO,P31,2015-12-24,Lab,Right,19,Day-1,50,18,32,2023-06-19 19:04:05.183477+00:00,2023-06-19 19:23:11.666561+00:00,tracking_test,2023-06-19 14:08:05+00:00,2023-06-19 14:08:20+00:00,15,"{'path': [, {880, 223.5}, {890.5, 226.50001525..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,CWALSL,P29,2018-07-25,Lab,Right,20,Day-1,20,9,11,2023-06-19 19:27:21.747335+00:00,2023-06-19 19:42:48.333426+00:00,tracking_test,2023-06-19 14:30:51+00:00,2023-06-19 14:30:52+00:00,1,"{'path': [, {49, 567.5}, {51, 569.5}, {63, 577..."
5,CWALSL,P29,2018-07-25,Lab,Right,20,Day-1,20,9,11,2023-06-19 19:27:21.747335+00:00,2023-06-19 19:42:48.333426+00:00,tracking_test,2023-06-19 14:31:07+00:00,2023-06-19 14:31:08+00:00,1,"{'path': [, {599, 387}, {42.5, 582.5}, {42.5, ..."
6,CWALSL,P29,2018-07-25,Lab,Right,20,Day-1,20,9,11,2023-06-19 19:27:21.747335+00:00,2023-06-19 19:42:48.333426+00:00,Round_Around,2023-06-19 14:34:49+00:00,2023-06-19 14:36:50+00:00,121,"[""lefttap_angle"": [272, 272, 271, 271, 271, 27..."
7,CWALSL,P29,2018-07-25,Lab,Right,20,Day-1,20,9,11,2023-06-19 19:27:21.747335+00:00,2023-06-19 19:42:48.333426+00:00,at_the_market,2023-06-19 14:38:08+00:00,2023-06-19 14:39:10+00:00,62,"'movement_paths': [""{'start_time': '2023-06-19..."
8,CWALSL,P29,2018-07-25,Lab,Right,20,Day-1,20,9,11,2023-06-19 19:27:21.747335+00:00,2023-06-19 19:42:48.333426+00:00,morse_code,2023-06-19 14:39:47+00:00,2023-06-19 14:42:48+00:00,181,"[""right_handmove"": [""type"": [""Tap"", ""Release"",..."

### Participants Age Analysis

In [10]:
from datetime import datetime
from datetime import date
def calculate_age(born):
    if(not isinstance(born, str)):
        return int(born)
    born = datetime.strptime(born, '%Y-%m-%d')
    today = date.today()
    return today.year - born.year - ((today.month, today.day) < (born.month, born.day))

In [11]:
df_data["age"] = df_data.apply(lambda x: calculate_age(x.age), axis=1)
df_data["age"].value_counts()

age
8     41
12    18
10    16
9     12
11     9
5      9
3      4
14     2
7      2
13     1
Name: count, dtype: int64

In [13]:
# Age Statistics
df_age = df_data[["name", "age"]]
df_age["age"].describe()

count    114.000000
mean       8.973684
std        2.336553
min        3.000000
25%        8.000000
50%        9.000000
75%       11.000000
max       14.000000
Name: age, dtype: float64

In [14]:
df_age["age"].median()

9.0

### Trials analysis

In [17]:
df_data["name"].value_counts()

name
P31    18
P30    18
P29    11
P6      6
P3      6
P26     6
P10     5
P13     4
P12     4
P9      4
P25     4
P27     4
P21     2
P18     2
P28     2
P11     2
P5      2
P24     2
P15     1
P16     1
P17     1
P19     1
P22     1
P20     1
P23     1
P2      1
P7      1
P4      1
P8      1
P14     1
Name: count, dtype: int64

In [18]:
df_data.groupby(['game_type']).size()

game_type
Coloring          2
Round_Around      9
at_the_market    11
morse_code       13
tracking_test    79
dtype: int64

In [19]:
df_data.groupby(['game_type', "name", "age"]).size()

game_type      name  age
Coloring       P13   3       1
               P30   12      1
Round_Around   P10   11      1
               P16   10      1
               P20   9       1
               P29   5       1
               P30   12      1
               P31   8       3
               P8    10      1
at_the_market  P13   3       1
               P15   10      1
               P19   9       1
               P25   8       1
               P28   14      1
               P29   5       1
               P30   12      2
               P31   8       2
               P7    9       1
morse_code     P12   9       1
               P14   13      1
               P2    8       1
               P22   10      1
               P23   9       1
               P25   8       1
               P27   8       1
               P28   14      1
               P29   5       1
               P30   12      1
               P31   8       2
               P4    10      1
tracking_test  P10   11      4
               P11   7       2
               P12   9       3
               P13   3       2
               P17   10      1
               P18   10      2
               P21   9       2
               P24   9       2
               P25   8       2
               P26   8       6
               P27   8       3
               P29   5       6
                     8       2
               P3    10      6
               P30   12     13
               P31   8      11
               P5    10      2
               P6    8       6
               P9    11      4
dtype: int64